### ISSUE TITLE
trim_quality usage

### ISSUE THREAD

**Issue by slazicoicr** [oicr-gsi/bam-qc-metrics#1]
This variable is used 

https://github.com/oicr-gsi/bam-qc-metrics/blob/f92385395e58f5ca35b1c1fb1de4b2097a05c92a/bam_qc_metrics/bam_qc.py#L132

where it means `-q, --trim-quality INT The BWA trimming parameter` (https://sourceforge.net/p/bio-bwa/mailman/message/25597301/)

The same variable is compared to the read MAPQ value

https://github.com/oicr-gsi/bam-qc-metrics/blob/f92385395e58f5ca35b1c1fb1de4b2097a05c92a/bam_qc_metrics/bam_qc.py#L74

These two uses are incompatible. 

`samtools` uses the `-q` flag differently depending on context. In `samtools view`: `-q INT Skip alignments with MAPQ smaller than INT [0]. `

**Comment by slazicoicr** [comment]
It would make sense to change the name of the parameter. To me, `trim_quality` implies that each read is being shortened based on quality. As `samtools view` is being used, this does not happen. The `samtools` docs has `Skip alignments with MAPQ smaller than INT [0].`, so maybe `skip_below_mapq`

**Comment by iainrb** [comment]
Yes, that makes sense. I'll rename the variable.

**Comment by iainrb** [comment]
Implemented in commit https://github.com/oicr-gsi/bam-qc-metrics/commit/7f3fd231815820f27cb6c6e088033b63a1f190e0
