### ISSUE TITLE
CIGAR of read reverse strand

### ISSUE THREAD

**Issue by slazicoicr** [oicr-gsi/bam-qc-metrics#2]
If the read is reversed by the aligner (flag 16), the CIGAR string will not match the cycle of the machine.

The iterarator needs to be reversed if flag 16 is set
https://github.com/oicr-gsi/bam-qc-metrics/blob/f92385395e58f5ca35b1c1fb1de4b2097a05c92a/bam_qc_metrics/bam_qc.py#L80

**Comment by iainrb** [comment]
Should be fixed by commit https://github.com/oicr-gsi/bam-qc-metrics/commit/59641a67cd8009ce1888012e21e49e51208e15d4
