### ISSUE TITLE
read_mark_duplicates_metrics

### ISSUE THREAD

**Issue by slazicoicr** [oicr-gsi/bam-qc-metrics#3]
https://github.com/oicr-gsi/bam-qc-metrics/blob/f92385395e58f5ca35b1c1fb1de4b2097a05c92a/bam_qc_metrics/bam_qc.py#L237

line will be a string, not digit

Example output for a MiSeq analysis

[GLCS_0001_Lv_R_PE_279_WG|1|190305_M00146_0024_000000000-D5N29.txt](https://github.com/oicr-gsi/bam-qc-metrics/files/3241978/GLCS_0001_Lv_R_PE_279_WG.1.190305_M00146_0024_000000000-D5N29.txt)

https://github.com/oicr-gsi/bam-qc-metrics/blob/f92385395e58f5ca35b1c1fb1de4b2097a05c92a/bam_qc_metrics/bam_qc.py#L215

Won't match `## METRICS CLASS	picard.sam.DuplicationMetrics`

For low coverage runs, `ESTIMATED_LIBRARY_SIZE` is left empty. Unfortunately, the Picard gods did not see fit to add a `\t` to signify an empty field, so the error below is raised

https://github.com/oicr-gsi/bam-qc-metrics/blob/f92385395e58f5ca35b1c1fb1de4b2097a05c92a/bam_qc_metrics/bam_qc.py#L240

**Comment by iainrb** [comment]
PR was merged. Issue should be resolved.
