### ISSUE TITLE
sample_rate parameter is not passed on

### ISSUE THREAD

**Issue by slazicoicr** [oicr-gsi/bam-qc-metrics#5]
The instance variable is always set to 1 at

https://github.com/oicr-gsi/bam-qc-metrics/blob/2f72712721c050303f8720c59d8e2f3337844fb6/bam_qc_metrics/bam_qc.py#L44

regardless of parameter. I think this needs changing to `self.sample_rate = sample_rate`

**Comment by iainrb** [comment]
No, that's just the default. The non-default parameter is set here: https://github.com/oicr-gsi/bam-qc-metrics/blob/2f72712721c050303f8720c59d8e2f3337844fb6/bam_qc_metrics/bam_qc.py#L58

The default is set to 1 so we have the same behaviour if the parameter is given as exactly 1, or not given at all.

**Comment by slazicoicr** [comment]
You are correct.
